version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: nestjs_mongo
    environment:
      - MONGODB_DATABASE=${DATABASE_NAME}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
